### ISSUE TITLE
flask run -> ValueError: Invalid app id

### ISSUE THREAD

**Issue by symant233** [neoighodaro/python-pusher-traffic-monitor#2]
System:
![image](https://user-images.githubusercontent.com/25316350/51855327-ef9a9600-2367-11e9-9b81-015350898561.png)
Error output:
```
(.venv) naya@LAPTOP-naya:~/monitor$ flask run
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/naya/monitor/.venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/click/core.py", line 1137, in
invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/flask/cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/flask/cli.py", line 293, in __init__
    self._load_unlocked()
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/flask/cli.py", line 377, in load_app
    raise_if_not_found=False)
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/home/naya/monitor/app.py", line 15, in <module>
    pusher = Pusher(app_id=u'PUSHER_APP_ID', key=u'PUSHER_APP_KEY', secret=u'PUSHER_APP_SECRER', cluster=u'PUSHER_APP_CLUSTER')
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/pusher/pusher.py", line 53, in __init__
    json_encoder, json_decoder, backend, **backend_options)
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/pusher/pusher_client.py", line 43, in __init__
    backend, **backend_options)
  File "/home/naya/monitor/.venv/lib/python3.5/site-packages/pusher/client.py", line 25, in __init__
    raise ValueError("Invalid app id")
ValueError: Invalid app id

```

**Comment by symant233** [comment]
Solved, you need to **register** a [pusher account](https://pusher.com/).
And add the user api key and so on to the app.py file.
Here is the website which contains a tutorial...
https://scotch.io/tutorials/build-a-web-traffic-monitor-with-python
